### ISSUE TITLE
update bmi_bmr.c

### ISSUE THREAD

**Issue by 99Pp** [99Pp/SDLC_Team4_HealthyMe#1]
For this file [bmi_bmr.c](3_Implementation/src/bmi_bmr.c) make sure the calcBMI() calcBMR() functions take all data as parameters,only the main function should interact with user. This will help in integrating with other modules later . 
The part which takes unit system into consideration is also missing.

**Comment by AjV1999** [comment]
I'm  working on this right now. Will update the files soon.

**Comment by AjV1999** [comment]
I have uploaded the updated files in the directory called Water+bmi
