### ISSUE TITLE
update workout.c

### ISSUE THREAD

**Issue by 99Pp** [99Pp/SDLC_Team4_HealthyMe#2]
In [workout.c](https://github.com/99Pp/SDLC_Team4_HealthyMe/blob/6aedd74a2b31d18e1dca127495f681cdd4f6168f/3_Implementation/workoutplan/workout.c) file the part which asks user "how much weight is to be reduced" should have a limit from (1   to  maximum reducible weight ) and also the case if user wants to reduce 0 kgs then no workout plan is to be shown

**Comment by ManasaKarur** [comment]
Updated workout function to limit the user input for the weight to be reduced (from 1 to maximum reducible weight) as per #2
