### ISSUE TITLE
gender is missing

### ISSUE THREAD

**Issue by Madhura-M** [99Pp/SDLC_Team4_HealthyMe#5]
[water.h](https://github.com/99Pp/SDLC_Team4_HealthyMe/blob/3d3e0590f09e6061abbc2f732766639e9267df88/3_Implementation/Water_intake/water.h)

add gender to your structure

**Comment by AjV1999** [comment]
I already did. It's in the new implementation I just uploaded.
Gender is an integer type variable,
1. Female, 2. Male

**Comment by AjV1999** [comment]
It's in the file Water_bmi
